### ISSUE TITLE
we always need simple examples

### ISSUE THREAD

**Issue by SKSON** [dotnet/docs.ko-kr#86]
there are only partial explanation, or too complicated full example..?
we need simple example, which we can understand easy.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 925c8fe9-ba0b-bd2c-cea0-9d851ece8825
* Version Independent ID: 41cafff5-6418-2e54-3a0d-ee29fb1fca1f
* Content: [ML.NET을 사용하여 아이리스 꽃 클러스터(클러스터링)](https://docs.microsoft.com/ko-kr/dotnet/machine-learning/tutorials/iris-clustering)
* Content Source: [docs/machine-learning/tutorials/iris-clustering.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/machine-learning/tutorials/iris-clustering.md)
* Product: **dotnet-ml**
* GitHub Login: @pkulikov
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #9634](https://github.com/dotnet/docs/issues/9634) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @SKSON 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/9634.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
