### ISSUE TITLE
Wrong example code in "Discards - C# Guide"

### ISSUE THREAD

**Issue by sopepos** [dotnet/docs.ko-kr#88]
There's no "switch" statement in example code of "Pattern matching with switch and is" section.

```csharp
   private static void ProvidesFormatInfo(object obj)         
   {
      if (obj is IFormatProvider fmt)
         Console.WriteLine($"{fmt} object");
      else if (obj is null) {
         Console.Write("A null object reference: ");
         Console.WriteLine("Its use could result in a NullReferenceException");
      }
      else
         Console.WriteLine($"Some object type without format information");
   }
```

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [무시 항목 - C# 가이드](https://docs.microsoft.com/ko-kr/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #9802](https://github.com/dotnet/docs/issues/9802) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @sopepos 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/9802.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
